[build]
  publish = "."

# Redirect all requests to depot-locator-new.html
[[redirects]]
  from = "/*"
  to = "/depot-locator-new.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://unpkg.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://unpkg.com https://cdnjs.cloudflare.com https://fonts.googleapis.com; img-src 'self' data: https://raw.githubusercontent.com https://*.tile.openstreetmap.org https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; connect-src 'self' https://nominatim.openstreetmap.org https://*.supabase.co https://cdn.jsdelivr.net; frame-src 'none'; object-src 'none';"
    Permissions-Policy = "geolocation=(self), camera=(), microphone=(), payment=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
